<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/csvimport.js', 'CSVImport'));
$this->headLink()->appendStylesheet($this->assetUrl('css/csvimport.css', 'CSVImport'));
$this->htmlElement('body')->appendAttribute('class', 'sidebar-open');
?>

<?php echo $this->pageTitle($this->translate('Map Elements · CSV Import')); ?>
<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <input type='submit' value='Next' />
</fieldset>
<input type='hidden' name='csvpath' value='<?php echo $csvpath; ?>' />

<a href='#' id='csv-import-basics' class='csv-import-fieldset-label'>
<?php echo $this->translate('Basic Import Settings'); ?>
<span class="collapse"></span>
</a>
<fieldset id='csv-import-basics-fieldset'>
    <?php echo $this->formCollection($form, false); ?>
</fieldset>

<a href='#' id='csv-import-columns-map' class='csv-import-fieldset-label'>
<?php echo $this->translate('Map CSV File Columns to Omeka S Data'); ?>
<span class="collapse"></span>
</a>
<div id='mapping-data'>
    <fieldset id="csv-import-columns-map-fieldset">
        <table>
            <thead>
                <tr>
                    <th><?php echo $this->translate("Csv Column"); ?></th>
                    <th><?php echo $this->translate("Mappings"); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($columns as $index=>$column): ?>
                <tr class="element mappable" data-element-id="<?php echo $index; ?>">
                    <td>
                        <h3><?php echo $column;?></h3>
<ul class='sidebar-chooser'>
<li><a href='#' class='button' data-sidebar='property-selector'>Map Properties</a></li>
<li><a href='#' class='button' data-sidebar='media-sidebar'>Media Import</a></li>
<li><a href='#' class='button' data-sidebar='flags-sidebar'>Set Flags</a></li>
<li><a href='#' class='button' data-sidebar='fake-module-sidebar'>(Module 1 stuff)</a></li>
</ul>
                    </td>
                    <td class="mapping element">
                        <ul class="mappings elements">
                        </ul>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
</div>
<?php echo $this->form()->closeTag($form); ?>

<?php
echo $this->propertySelector('Select property to map. Click a column heading as the target, then select the properties for it.', true);
?>

<div id='flags-sidebar' class='flags sidebar'>
    <ul>
        <li data-flag='column-url'>
            <div class='description'>Import this data as a URL value type.</div>
            <span>URL?</span>
        </li>
        <li data-flag='column-multivalue'>
            <div class='description'>This column contains multiple values for a property. Double-check the separator for multiple values.</div>
            <span>Multiple Values?</span>
        </li>
    </ul>
</div>

<div id='media-sidebar' class='sidebar'>
    <p>Media Importing (eventually auto-built)</p>
    <ul>
        <li data-flag='column-file'>
            <div class='description'>Data in this column gives URLs to files to import.</div>
            <span>File URL</span>
        </li>
        <li data-flag='column-oembed'>
            <div class='description'>Data in this column gives URLs to oEmbed sources.</div>
            <span>oEmbed</span>
        </li>
        <li data-flag='column-youtube'>
            <div class='description'>Data in this column gives URLs to YouTube Videos</div>
            <span>YouTube</span>
        </li>
        <li data-flag='column-html'>
            <div class='description'>Data in this column gives HTML.</div>
            <span>HTML</span>
        </li>
        <li data-flag='column-iiif'>
            <div class='description'>Data in this column gives URLs to IIIF image.</div>
            <span>IIIF Image</span>
        </li>
    </ul>

</div>

<div id='fake-module-sidebar' class='sidebar'>
A module puts stuff here

</div>
