<?php
$form->prepare();
$escapeHtml = $this->plugin('escapeHtml');
$this->headScript()->appendFile($this->assetUrl('js/csvimport.js', 'CSVImport'));
$this->headLink()->appendStylesheet($this->assetUrl('css/csvimport.css', 'CSVImport'));
$this->htmlElement('body')->appendAttribute('class', 'sidebar-open');
?>

<?php echo $this->pageTitle($this->translate('Map Elements · CSV Import')); ?>
<?php echo $this->form()->openTag($form); ?>
<fieldset id='page-actions'>
    <input type='submit' value='Next' />
</fieldset>
<input type='hidden' name='csvpath' value='<?php echo $csvpath; ?>' />
<div id='mapping-data'>
    <fieldset id="csv-import-elements-map-fieldset">
        <table>
            <thead>
                <tr>
                    <th><?php echo $this->translate("Csv Heading"); ?></th>
                    <th><?php echo $this->translate("Mapped Properties"); ?></th>
                    <th><?php echo $this->translate("Uri"); ?></th>
                    <th><?php echo $this->translate("File"); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($columns as $index=>$column): ?>
                <tr class="element mappable" data-element-id="<?php echo $index; ?>">
                    <td><?php echo $column;?></td>
                    <td class="mapping element">
                        <ul class="mappings elements">
                        </ul>
                    </td>
                    <td>
                        <input type="checkbox" name="column-uri[<?php echo $index; ?>]"></input>
                    </td>
                    <td>
                        <input type="checkbox" name="column-file[<?php echo $index; ?>]"></input>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
</div>
<?php echo $this->form()->closeTag($form); ?>

<?php
echo $this->propertySelector('Select property to map. Click a column heading as the target, then select the properties for it.', true);
?>