<?php
$escape = $this->plugin('escapeHtml');
?>
<div id="property-selector" class="mapping-group">
    <a href="#" class="expand" aria-label="<?php echo $this->translate('Expand'); ?>">
        <h4><?php echo $escape($propertySelectorText); ?></h4>
    </a>
    <div class="collapsible">
        <input type="text" class="selector-filter" placeholder="<?php echo $this->translate('Filter properties'); ?>">
        <ul class="selectable-list">
            <?php foreach ($vocabularies as $vocabulary): ?>
            <?php
            $properties = $vocabulary->properties();
            if (!$properties) {
                // Do not render vocabularies without properties.
                continue;
            }
            ?>
            <li class='selector-parent'
                data-vocabulary-id="<?php echo $escape($vocabulary->id()); ?>">
                <span><?php echo $escape($this->translate($vocabulary->label())); ?></span> (<span class="selector-child-count"><?php echo count($vocabulary->properties()); ?></span>)
                <ul>
                    <?php foreach ($properties as $property): ?>
                    <li class='selector-child'
                        data-child-search="<?php echo $escape($this->translate($property->label())); ?>"
                        data-property-id="<?php echo $escape($property->id()); ?>"
                        data-property-term="<?php echo $escape($property->term()); ?>">
                        <div class="description">
                            <p class="o-icon-info"><span class="screen-reader-text"><?php echo $this->translate('More info'); ?></span></p>
                            <p class="field-comment"><?php echo $escape($this->translate($property->comment())); ?></p>
                        </div>
                        <span class="selectable"><?php echo $escape($this->translate($property->label())); ?></span>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
