
<div id='item-data' class='sidebar flags'>
    <a href='#' class='sidebar-close o-icon-close'><span class='screen-reader-text'>Close Me</span></a>
    <h3>Item Data: </h3>

    <p>Data from this column applies to the entire item being imported.</p>
    <p>Settings here will override any corresponding settings in Basic Import Settings.</p>
    <ul>
        <li data-flag='column-itemset-id' data-flag-type='item-data'>
            <a href='#' class='button'><span>Item Set ID</span></a>
        </li>
        <li data-flag='column-resourcetemplate' data-flag-type='item-data'>
            <a href='#' class='button'><span>Resource Template Name</span></a>
        </li>
        <li data-flag='column-resourceclass' data-flag-type='item-data'>
            <a href='#' class='button'><span>Resource Class Term</span></a>
        </li>
        
       <?php if( ($userRole == 'global_admin') || ($userRole == 'site_admin')): ?>

            <li data-flag='column-owneremail'>
                <a href='#' class='button'><span>Owner Email Address</span></a>
            </li>
       <?php endif; ?>
       
    </ul>
        
    <div class='item-mapping options'>
        <h4>Options</h4>
        <a href='#' class='button column-multivalue'><span>Use multivalue separator</span></a>
        <p>(Only applies to Item Set ID)</p>
    </div>
</div>
