<?php
$translate = $this->plugin('translate');
?>
<div id="add-mapping" class="selector sidebar flags">
    <div class="confirm-main">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close'); ?></span></a>
        <h3><?php echo $translate('Add mapping: '); ?></h3>
        <?php
        foreach($mappings as $mapping) {
            echo $mapping->getSidebar($this);
        }
        ?>
    </div>
    <div class="confirm-panel">
        <button type="button"><?php echo $translate('Apply changes'); ?></button>
    </div>
</div>
