
<div id='media-import' class='sidebar flags'>
    <a href='#' class='sidebar-close o-icon-close'><span class='screen-reader-text'>Close Me</span></a>
    <h3>Media Importing: </h3>
    <ul>

    <?php foreach($mediaForms as $type=>$mediaForm): ?>
        <li data-flag='<?php echo $type; ?>' data-flag-type='media'>
            <a href='#' class='button'><span><?php echo $mediaForm['label']; ?></span></a>
        </li>
    <?php endforeach; ?>

    </ul>
    
    <div class='media-mapping options'>
        <h4>Options</h4>
        <a href='#' class='button column-multivalue'><span>Use multivalue separator</span></a>
    </div>

</div>
