<div id="column-options" class="sidebar">
    <div class="confirm-main">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
        <h3 class="batch-edit-heading"><?php echo $this->translate('Batch edit column options:'); ?></h3>
        <h3 class="single-column-heading"><?php echo $this->translate('Column options:'); ?></h3>

        <p class="batch-edit-description"><?php echo $this->translate('Highlighted options will apply to selected column headers. Reset an option to cancel changes.'); ?></p>

        <?php if (empty($resourceType) || in_array($resourceType, ['items', 'item_sets', 'media', 'resources'])): ?>
        <div class="multivalue option one-line">
            <label for="multivalue"><?php echo $this->translate('Use multivalue separator'); ?></label>
            <div class="option-inputs">
                <input type="checkbox" data-column-option="column-multivalue" name="multivalue" id="multivalue">
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
        <?php endif; ?>

        <div class="private-values option one-line">
            <label for="private-values"><?php echo $this->translate('Import values as private'); ?></label>
            <div class="option-inputs">
                <input type="checkbox" data-column-option="column-private-values" id="private-values">
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
        <div class="language option">
            <label for="value-language"><?php echo $this->translate('Language'); ?></label>
            <span class="description"><?php echo $this->translate('This will override language settings in basic import settings.'); ?></span>
            <div class="option-inputs">
                <input id="value-language" class="validate-language active" type="text">
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
        <div class="data-type option">
            <label for="column-data-type"><?php echo $this->translate('Data type'); ?></label>
            <div class="option-inputs">
                <select id="column-data-type" data-column-option="column-data-type">
                <?php foreach ($dataTypes as $id => $label): ?>
                    <?php if ($id === 'literal') { $id = ''; } ?>
                    <option value="<?php echo $this->escapeHtml($id); ?>"><?php echo $this->translate($label); ?></option>
                <?php endforeach; ?>
                </select>
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
        <div class="resource-identifier-property option">
            <label for="resource-identifier-property"><?php echo $this->translate('Resource identifier property'); ?></label>
            <span class="description"><?php echo $this->translate('This only takes effect when using the "Omeka resource" data type above.'); ?></span>
            <div class="option-inputs">
                <?php echo $this->propertySelect([
                    'name' => 'resource-identifier-property',
                    'attributes' => [
                        'id' => 'resource-identifier-property',
                        'data-column-option' => 'column-resource-identifier-property',
                    ],
                    'options' => [
                        'empty_option' => 'Internal ID',
                        'term_as_value' => true,
                   ],
                ]); ?>
            </div>
        </div>
    </div>
    <div class="confirm-panel">
        <button type="button"><?php echo $this->translate("Apply changes"); ?></button>
    </div>
</div>
