<div id="column-options" class="sidebar">
    <div class="confirm-main">
        <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
        <h3 class="batch-edit-heading"><?php echo $this->translate('Batch edit column options:'); ?></h3>
        <h3 class="single-column-heading"><?php echo $this->translate('Column options:'); ?></h3>

        <p class="batch-edit-description"><?php echo $this->translate('Highlighted options will apply to selected column headers. Reset an option to cancel changes.'); ?></p>

        <?php if (empty($resourceType) || in_array($resourceType, ['items', 'resources'])): ?>
        <div class="multivalue option">
            <label for="multivalue"><?php echo $this->translate('Use multivalue separator'); ?></label>
            <div class="option-inputs">
                <input type="checkbox" data-column-option="column-multivalue" name="multivalue" id="multivalue">
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
        <?php endif; ?>

        <div class="language option">
            <label for="value-language"><?php echo $this->translate('Language'); ?></label>
            <span class="description"><?php echo $this->translate('This will override language settings in basic import settings.'); ?></span>
            <div class="option-inputs">
                <input id="value-language" class="value-language active" type="text">
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>

        <div class="import option">
            <label for="column-import"><?php echo $this->translate('Data type'); ?></label>
            <div class="option-inputs">
                <select name="column-import" id="column-import" data-column-option="column-import">
                    <option class="button column-text" value="default"><?php echo $this->translate('Import as text (default)'); ?></option>
                    <option class="button column-url" value="column-url"><?php echo $this->translate('Import as URL reference'); ?></option>
                    <option class="button column-reference" value="column-reference"><?php echo $this->translate('Import as Omeka S resource ID'); ?></option>
                </select>
            </div>
            <a href="#" class="reset-link"><?php echo $this->translate('Reset'); ?></a>
        </div>
    </div>
    <div class="confirm-panel">
        <button type="button"><?php echo $this->translate("Apply changes"); ?></button>
    </div>
</div>