<div id="resource-data" class="sidebar flags">
    <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $this->translate('Close'); ?></span></a>
    <h3><?php echo $this->translate('Resource data:'); ?></h3>
    <p><?php echo $this->translate('Data from this column applies to the entire resource being imported.'); ?></p>
    <p><?php echo $this->translate('Settings here will override any corresponding settings in Basic import settings.'); ?></p>
    <ul>
        <li data-flag="column-resourcetemplate" data-flag-type="resource-data">
            <a href="#" class="button"><span><?php echo $this->translate('Resource template name'); ?></span></a>
        </li>
        <li data-flag="column-resourceclass" data-flag-type="resource-data">
            <a href="#" class="button"><span><?php echo $this->translate('Resource class term'); ?></span></a>
        </li>
       <?php if (in_array($userRole, ['global_admin', 'site_admin'])): ?>
        <li data-flag="column-owneremail" data-flag-type="resource-data">
            <a href="#" class="button"><span><?php echo $this->translate('Owner email address'); ?></span></a>
        </li>
       <?php endif; ?>
        <li data-flag="column-ispublic" data-flag-type="resource-data">
            <a href="#" class="button"><span><?php echo $this->translate('Visibility public/private'); ?></span></a>
        </li>
    </ul>
</div>
