<?php
$translate = $this->plugin('translate');
?>
<div id="resource-data" class="mapping-group">
    <a href="#" class="expand" aria-label="Expand">
        <h4><?php echo $translate('Resource data'); ?></h4>
    </a>
    <div class="collapsible">
        <span class="description"><?php echo $translate('Data from this column applies to the entire resource being imported. Settings here will override any corresponding settings in "Basic Settings".'); ?></span>
        <div class="resource-mapping mappings">
            <?php $resourceTypeLabels = $form->getResourceTypeLabels(); ?>
            <div class="toggle-nav">
                <button type="button" data-toggle-selector="#specific-data" class="toggle button active" disabled><?php echo $translate(sprintf('%s data', $translate($resourceTypeLabels[$resourceType]))); ?></button>
                <button type="button" data-toggle-selector="#generic-data" class="toggle button"><?php echo $translate('Generic data'); ?></button>
            </div>

            <div id="specific-data" class="active toggle-view">

                <?php if ($resourceType == 'resources'): ?>
                <?php
                $element = $form->get('data_resource_type_select');
                $form->remove('data_resource_type_select');
                ?>
                <div class="resource-type-select">
                    <?php echo $this->formLabel($element); ?>
                    <span class="description"><?php echo $element->getOption('info'); ?></span>
                    <?php echo $this->formElement($element); ?>
                </div>
                <?php endif; ?>

                <?php if (empty($resourceType) || in_array($resourceType, ['item_sets', 'resources'])): ?>
                <?php
                $element = $form->get('additions');
                $form->remove('additions');
                ?>
                <div class="mapping additions item-sets">
                    <?php echo $this->formLabel($element); ?>
                    <?php echo $this->formElement($element); ?>
                </div>
                <?php endif; ?>

                <?php if (empty($resourceType) || in_array($resourceType, ['items', 'resources'])): ?>
                <?php
                $element = $form->get('column-item_set_property');
                $form->remove('column-item_set_property');
                ?>
                <div class="mapping property items">
                    <?php echo $this->formLabel($element); ?>
                    <?php echo $this->formElement($element); ?>
                </div>
                <?php endif; ?>

                <?php if (empty($resourceType) || in_array($resourceType, ['media', 'resources'])): ?>
                <?php
                $element = $form->get('column-item_property');
                $form->remove('column-item_property');
                ?>
                <div class="mapping property media">
                    <?php echo $this->formLabel($element); ?>
                    <span class="description"><?php echo $element->getOption('info'); ?></span>
                    <?php echo $this->formElement($element); ?>
                </div>
                <?php endif; ?>
            </div>

            <?php
            /** @var \Zend\Form\Element\Select $element */
            $element = $form->get('resource_data');
            $form->remove('resource_data');
            ?>
            <div id="generic-data" class="toggle-view">
                <div class="mapping">
                    <?php
                    // A data "flag-name" should be added for each select option,
                    // and the option value should be "1".
                    // TODO Fix javascript to use a standard value without flag.
                    // echo $this->formElement($element);
                    ?>
                    <select name="resource_data" class="flags" data-flag-class="resource-data" data-flag-label="<?php echo $translate('Data'); ?>">
                    <?php foreach ($element->getValueOptions() as $key => $label): ?>
                        <?php if (empty($key)): ?>
                        <option><?php echo $label; ?></option>
                        <?php else: ?>
                        <option value="1" data-flag-name="<?php echo $key; ?>"><?php echo $label; ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>

        <div>
            <?php // Remaining elements (none by default). ?>
            <?php echo $this->formCollection($form); ?>
        </div>
    </div>
</div>
