<div id="user-data" class="sidebar always-open flags">
    <h3><?php echo $this->translate('Users info'); ?></h3>
    <ul>
        <li data-flag="column-user_email">
            <a href="#" class="button"><span><?php echo $this->translate('Email'); ?></span></a>
        </li>
        <li data-flag="column-user_name">
            <a href="#" class="button"><span><?php echo $this->translate('Display name'); ?></span></a>
        </li>
        <li data-flag="column-user_role">
            <a href="#" class="button"><span><?php echo $this->translate('Role'); ?></span></a>
        </li>
    </ul>
</div>
