<div id='users-sidebar' class='sidebar always-open flags'>
    <h3>Users Info</h3>
    <ul>
        <li data-flag='column-user-email'>
            <a href='#' class='button'><span>Email</span></a>
        </li>
        <li data-flag='column-user-displayname'>
            <a href='#' class='button'><span>Display Name</span></a>
        </li>
        <li data-flag='column-user-role'>
            <a href='#' class='button'><span>Role</span></a>
        </li>
    </ul>
</div>
