<div id="item-set-resource-data" class="mapping-group">
    <a href="#" class="expand" aria-label="Expand">
        <h4><?php echo $this->translate('Item set-specific data'); ?></h4>
    </a>
    <div class="collapsible">
        <div class="mapping additions item-sets one-line">
            <label for="additions"><?php echo $this->translate('Open to additions'); ?></label>
            <input name="additions" id="additions" type="checkbox" data-flag-class="resource-data" data-flag-name="column-is_open" data-flag-label="<?php echo $this->translate('Open to additions'); ?>" value="1">
        </div>
    </div>
</div>
