<div id="user-data" class="mapping-group">
    <a href="#" class="expand" aria-label="Expand">
        <h4><?php echo $this->translate('Users info'); ?></h4>
    </a>
    <div class="collapsible">
        <select data-flag-class="user-data" data-flag-label="<?php echo $this->translate('Users info'); ?>">
            <option value="default"><?php echo $this->translate('Select below'); ?></option>
            <option value="1" data-flag-name="column-user_email"><?php echo $this->translate('Email'); ?></option>
            <option value="1" data-flag-name="column-user_name"><?php echo $this->translate('Display name'); ?></option>
            <option value="1" data-flag-name="column-user_role"><?php echo $this->translate('Role'); ?></option>
        </select>
    </div>
</div>
