<?php $form->prepare(); ?>

<?php echo $this->pageTitle($this->translate('Select mapping model'), 3); ?>

<?php echo $this->form()->openTag($form); ?>

<?php echo $this->formCollection($form); ?>

<fieldset>
    <button type="button" id='mapping-select-button'>
        <?php echo $this->translate('Select mapping model'); ?>
    </button>
</fieldset>

<?php echo $this->form()->closeTag($form); ?>

